dist: focal
sudo: required

language: c
os: linux
compiler: gcc

install:
  # cmake, clang-form, valgrind
  - sudo apt update
  - sudo apt install clang-format
  - sudo apt install valgrind
  - sudo apt install cmake
  # GTest
  - sudo apt install libgtest-dev
  - sudo apt install cppcheck
  # configure after installation
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo apt-get install cppcheck
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cppcheck mmain.c consist_static/logic_consist.c consist_static/logic_consist.h parallel_dynamic/logic_parallel.c parallel_dynamic/logic_parallel.h input_output.h file_creation.c file_creation.h
  - mkdir build
  - cd build
  - ls
  - cmake
  - cd ../Google_tests
  - ls
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes chmod a+x ./tests.cpp
  - chmod a+x ./tests.cpp

after_script:
  bash <(curl -s https://codecov.io/bash) -t 42dea440-97af-45d1-84c1-e8b440fab0b4